Lets build for Vayu
Signed-off-by: rahul9999xda <rahul9999xda@gmail.com>

diff --git a/build b/build
--- a/build
+++ b/build
@@ -4,7 +4,7 @@ cd /tmp/rom # Depends on where source got synced
 rm -rf device/generic/opengl-transport
 # Normal build steps
 . build/envsetup.sh
-lunch derp_X00T-userdebug
+lunch derp_vayu-userdebug
 export CCACHE_DIR=/tmp/ccache
 export CCACHE_EXEC=$(which ccache)
 export USE_CCACHE=1
@@ -13,14 +13,14 @@ ccache -o compression=true # Will save times and data to download and upload cca
 ccache -z # Clear old stats, so monitor script will provide real ccache statistics
 
 # Next 8 lines should be run first to collect ccache and then upload, after doning it 1 or 2 times, our ccache will help to build without these 8 lines Sepolicy Fix.
-#mka api-stubs-docs || echo no problem, we need ccache
-#mka system-api-stubs-docs || echo no problem we need ccache
-#mka test-api-stubs-docs || echo no problem, we need ccache
-#mka derp -j8 & # dont remove that '&'
-#sleep 80m
-#kill %1
-#ccache -s
-#and dont use below codes for first 1 or 2 times, to get ccache uploaded,
+mka api-stubs-docs || echo no problem, we need ccache
+mka system-api-stubs-docs || echo no problem we need ccache
+mka test-api-stubs-docs || echo no problem, we need ccache
+mka derp -j8 & # dont remove that '&'
+sleep 80m
+kill %1
+ccache -s
+and dont use below codes for first 1 or 2 times, to get ccache uploaded,
 
 
 # upload function for uploading rom zip file! I don't want unwanted builds in my google drive haha!
@@ -43,13 +43,13 @@ id=472743155 # Your telegram id
 # Upload rom zip file if succeed to build! Send notification to tg! And send shell to tg if build fails!
 
 # Let's compile by parts! Coz of ram issue!
-mka api-stubs-docs || echo no problem
-mka system-api-stubs-docs || echo no problem
-mka test-api-stubs-docs || echo no problem
-
-mka derp -j8 \
-	&& send_zip=$(up out/target/product/X00T/*zip) && tg $id "Build Succeed!
-$send_zip" \
-	|| tmate -S /tmp/tmate.sock new-session -d && tmate -S /tmp/tmate.sock wait tmate-ready && send_shell=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}') && tg $id "Build Failed" && tg $id "$send_shell" && ccache -s && sleep 2h
-ccache -s # Let's print ccache statistics finally
+#mka api-stubs-docs || echo no problem
+#mka system-api-stubs-docs || echo no problem
+#mka test-api-stubs-docs || echo no problem
+#
+#mka derp -j8 \
+#	&& send_zip=$(up out/target/product/vayu/*zip) && tg $id "Build Succeed!
+#$send_zip" \
+#	|| tmate -S /tmp/tmate.sock new-session -d && tmate -S /tmp/tmate.sock wait tmate-ready && send_shell=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}') && tg $id "Build Failed" && tg $id "$send_shell" && ccache -s && sleep 2h
+#ccache -s # Let's print ccache statistics finally
 
